### ISSUE TITLE
AGPL License in dependencies

### ISSUE THREAD

**Issue by wschaef** [evernat/grails-melody-plugin#24]
The plugin has 3 dependencies. One of the them (compile ("com.lowagie:itext:2.1.7") ) is under AGPL license. That means, that the plugin itself has to be under AGPL license too.
There are two options for solution:
1. remove itext dependency
2. make the license for plugin AGPL (will make this great plugin unusable for closed source developerst)

**Comment by evernat** [comment]
Yes the plugin has a dependency on "com.lowagie:itext:2.1.7" (iText v2.1.7).
And no, it is not under AGPL, because "com.lowagie:itext:2.1.7" is under MPL or LGPL at your choice.

iText v5 and later are licensed under commercial OR AGPL as said at:
http://itextpdf.com/pricing
or https://repo1.maven.org/maven2/com/itextpdf/itextpdf/5.5.6/itextpdf-5.5.6.pom

But iText v2.1.7 is licensed under MPL, or at your choice LGPL, as said at:
https://repo1.maven.org/maven2/com/lowagie/itext/2.1.7/itext-2.1.7.pom

You are confused by the switch of license between v2.1.7 and v5 decided by the authors of iText.
Can we close this issue?

**Comment by wschaef** [comment]
OK
Thank you for the answer!
